# --- The Database Deployment ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: invincible-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invincible-db
  template:
    metadata:
      labels:
        app: invincible-db
    spec:
      containers:
      - name: db-container
        image: kallurayarohith/the-invincible-cloud:db-v1
        ports:
        - containerPort: 5432 
---
# --- The Web App Deployment ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: invincible-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invincible-web
  template:
    metadata:
      labels:
        app: invincible-web
    spec:
      containers:
      - name: web-container
        image: kallurayarohith/the-invincible-cloud:web-v1
        ports:
        - containerPort: 80